#
# Generated by erpcgen 1.13.0 on Fri Feb 14 13:57:33 2025.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for TextService
class ITextService(object):
    SERVICE_ID = 1
    PRINTTEXT_ID = 1
    STOPSERVER_ID = 2

    def printText(self, text):
        raise NotImplementedError()

    def stopServer(self):
        raise NotImplementedError()


