/** 
 * Generated by erpcgen 1.13.0 on Fri Feb 14 13:57:33 2025.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */ 

package org.example.hello_world.interfaces;




import io.github.embeddedrpc.erpc.auxiliary.Reference;

import java.util.List;

public interface ITextService {
    int SERVICE_ID = 1;
    int PRINTTEXT_ID = 1;
    int STOPSERVER_ID = 2;

    boolean printText(String text);
    void stopServer();
}



