/*
 * Generated by erpcgen 1.13.0 on Fri Feb 14 14:15:26 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hello_world_server_hpp_)
#define _hello_world_server_hpp_

#include "hello_world_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11300 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for TextService.
 */
class TextService_service : public erpc::Service
{
public:
    TextService_service(TextService_interface *_TextService_interface);

    virtual ~TextService_service();

    /*! @brief return service interface handler. */
    TextService_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    TextService_interface *m_handler;
    /*! @brief Server shim for printText of TextService interface. */
    erpc_status_t printText_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);

    /*! @brief Server shim for stopServer of TextService interface. */
    erpc_status_t stopServer_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _hello_world_server_hpp_
