/*
 * Generated by erpcgen 1.13.0 on Fri Feb 14 14:15:26 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hello_world_interface_hpp_)
#define _hello_world_interface_hpp_

#include "hello_world_common.hpp"

namespace erpcShim
{


// Abstract base class for TextService
class TextService_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_printTextId = 1;
        static const uint8_t m_stopServerId = 2;

        virtual ~TextService_interface(void);

        virtual bool printText(const char * text) = 0;

        virtual void stopServer(void) = 0;
private:
};
} // erpcShim


#endif // _hello_world_interface_hpp_
