/*
 * Generated by erpcgen 1.13.0 on Fri Feb 14 14:15:26 2025.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hello_world_client_hpp_)
#define _hello_world_client_hpp_

#include "hello_world_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class TextService_client: public TextService_interface
{
    public:
        TextService_client(erpc::ClientManager *manager);

        virtual ~TextService_client();

        virtual bool printText(const char * text);

        virtual void stopServer(void);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _hello_world_client_hpp_
