/** 
 * Generated by erpcgen 1.13.0 on Fri Feb 14 13:57:33 2025.
 * 
 * AUTOGENERATED - DO NOT EDIT
 */
 package org.example.hello_world.common;





import java.util.ArrayList;
import java.util.List;

public final class Constants {

    private Constants() {
    }
}

